### ISSUE TITLE
Undefined function or variable 'inpolyhedron'

### ISSUE THREAD

**Issue by moraesfernanda** [cnnp-lab/CorticalFoldingAnalysisTools#1]
Hello,
I am trying to run the estimateScale() function, and it seems to need a function not included in MATLAB or in the Image Processing Toolbox. Is this correct? My bet is to download from this website https://www.mathworks.com/matlabcentral/fileexchange/37856-inpolyhedron-are-points-inside-a-triangulated-volume
If this is correct, I would recommend including this in the future README file for this function.

Best regards,
Fernanda

**Comment by yujiangwang** [comment]
It's now added to the Scales folder :)
